permit_join: true
homeassistant: false
mqtt:
  server: mqtt://smb:1883
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
  adapter: ember
frontend:
  port: 8080
advanced:
  log_level: debug
  log_rotation: false
  log_output:
    - console
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
advanced.network_key: GENERATE
device_options:
  legacy: false
devices:
  '0xa4c1380da8740c0c':
    friendly_name: '0xa4c1380da8740c0c'
  '0xd44867fffe4c30d0':
    friendly_name: '0xd44867fffe4c30d0'
  '0x84b4dbfffe0438af':
    friendly_name: '0x84b4dbfffe0438af'
